In [22]:
import pandas as pd
import numpy as np
import array

In [65]:
#these files are created in the R script. 

lists1t1pl = pd.read_csv("c:/MachineLearningWork/news1t1pL.csv")
lists1t1pc = pd.read_csv("c:/MachineLearningWork/news1t1pC.csv")
lists2t1pl = pd.read_csv("c:/MachineLearningWork/news2t1pL.csv")
lists2t1pc = pd.read_csv("c:/MachineLearningWork/news2t1pc.csv")
lists3t1pl = pd.read_csv("c:/MachineLearningWork/news3t1pL.csv")
lists3t1pc = pd.read_csv("c:/MachineLearningWork/news3t1pC.csv")
#lists4t1pl = pd.read_csv("c:/MachineLearningWork/s4t1pL.csv")
#lists4t1pc = pd.read_csv("c:/MachineLearningWork/s4t1pC.csv")
#lists5t1pl = pd.read_csv("c:/MachineLearningWork/s5t1pL.csv")
#lists5t1pc = pd.read_csv("c:/MachineLearningWork/s5t1pC.csv")
#lists6t1pl = pd.read_csv("c:/MachineLearningWork/s6t1pL.csv")
#lists6t1pc = pd.read_csv("c:/MachineLearningWork/s6t1pC.csv")
#lists7t1pl = pd.read_csv("c:/MachineLearningWork/s7t1pL.csv")
#lists7t1pc = pd.read_csv("c:/MachineLearningWork/s7t1pC.csv")
#lists8t1pl = pd.read_csv("c:/MachineLearningWork/s8t1pL.csv")
#lists8t1pc = pd.read_csv("c:/MachineLearningWork/s8t1pC.csv")
list = pd.read_csv("c:/MachineLearningWork/tva_output.csv")

In [66]:
lists3t1pc

    Unnamed: 0  Point.Forecast     Lo.80     Hi.80     Lo.95     Hi.95
0     2.833333        3.107214  2.679743  3.534685  2.453454  3.760975
1     2.875000        3.024550  2.553403  3.495696  2.303994  3.745106
2     2.916667        3.162464  2.682455  3.642473  2.428353  3.896575
3     2.958333        3.140446  2.658555  3.622338  2.403457  3.877436
4     3.000000        3.122946  2.640652  3.605241  2.385340  3.860552
5     3.041667        3.287529  2.805148  3.769911  2.549791  4.025268
6     3.083333        3.448339  2.965939  3.930738  2.710572  4.186106
7     3.125000        3.288546  2.806142  3.770950  2.550773  4.026319
8     3.166667        2.926853  2.444448  3.409258  2.189079  3.664627
9     3.208333        3.150642  2.668237  3.633047  2.412867  3.888416
10    3.250000        3.286169  2.803764  3.768574  2.548394  4.023943
11    3.291667        2.934730  2.452325  3.417135  2.196955  3.672504
12    3.333333        2.912883  2.430478  3.395287  2.175108  3.650657
13    3.375000        2.753697  2.271293  3.236102  2.015923  3.491472
14    3.416667        2.781716  2.299311  3.264121  2.043941  3.519490
15    3.458333        2.469264  1.986859  2.951669  1.731489  3.207038
16    3.500000        2.640048  2.157644  3.122453  1.902274  3.377823
17    3.541667        2.482711  2.000306  2.965116  1.744937  3.220486
18    3.583333        3.084270  2.601865  3.566675  2.346495  3.822045
19    3.625000        2.993414  2.511009  3.475819  2.255639  3.731188
20    3.666667        2.970337  2.487932  3.452742  2.232562  3.708112
21    3.708333        3.045533  2.563128  3.527938  2.307758  3.783308
22    3.750000        3.353696  2.871291  3.836101  2.615922  4.091471
23    3.791667        3.159819  2.677414  3.642224  2.422044  3.897593
24    3.833333        3.316013  2.671462  3.960564  2.330257  4.301768

In [67]:
s1t1_predict_l = lists1t1pl.iloc[:, 1]
s1t1_predict_c = lists1t1pc.iloc[:, 1]
s2t1_predict_l = lists2t1pl.iloc[:, 1]
s2t1_predict_c = lists2t1pc.iloc[:, 1]
s3t1_predict_l = lists3t1pl.iloc[:, 1]
s3t1_predict_c = lists3t1pc.iloc[:, 1]
#s4t1_predict_l = lists4t1pl.iloc[:, 1]
#s4t1_predict_c = lists4t1pc.iloc[:, 1]
#s5t1_predict_l = lists5t1pl.iloc[:, 1]
#s5t1_predict_c = lists5t1pc.iloc[:, 1]
#s6t1_predict_l = lists6t1pl.iloc[:, 1]
#s6t1_predict_c = lists6t1pc.iloc[:, 1]
#s7t1_predict_l = lists7t1pl.iloc[:, 1]
#s7t1_predict_c = lists7t1pc.iloc[:, 1]
#s8t1_predict_l = lists8t1pl.iloc[:, 1]
#s8t1_predict_c = lists8t1pc.iloc[:, 1]

In [26]:
s1t1_predict_l

0     1.796220
1     1.846968
2     1.812654
3     1.820764
4     1.825181
5     1.824951
6     1.831312
7     1.818527
8     1.799975
9     1.824579
10    1.793649
11    1.799717
12    1.886131
13    1.831378
14    1.923837
15    1.835791
16    1.822031
17    1.845205
18    1.834487
19    1.862122
20    1.906595
21    1.815245
Name: Point.Forecast, dtype: float64

In [8]:
list

,Timestamp,Server,Tactic,Latency,Cost,Reliability,Hour,Total Hours
0,32:53.4,1,1,1.716679,15.9,1,16,0
1,33:01.9,1,2,8.534772,12.3,1,16,0
2,33:02.1,1,3,0.176431,28.8,1,16,0
3,33:08.5,1,4,6.426049,26.7,1,16,0
4,33:17.9,1,5,9.365804,2.1,1,16,0
...,...,...,...,...,...,...,...,...
50623,07:55.1,3,2,3.534241,25.3,1,11,67
50624,07:55.3,3,3,0.179088,25.3,1,11,67
50625,08:01.7,3,4,6.407070,26.8,1,11,67
50626,08:02.0,3,5,0.303190,25.8,1,11,67
50627,08:08.7,1,1,1.718984,9.5,1,11,67

In [68]:
masterArray = np.zeros((50628,9))

In [69]:
index = list.iloc[:, 0]
hours = list.iloc[:, 7]
latency = list.iloc[:, 3]
cost = list.iloc[:,4]
rel = list.iloc[:,5]
preL = list.iloc[:,8]
preC = list.iloc[:,9]
server1 = list.iloc[:,1]
#server2 = list.iloc[:,15]
#server3 = list.iloc[:,16]
#server4 = list.iloc[:,17]
#server5 = list.iloc[:,18]
#server6 = list.iloc[:,19]
#server7 = list.iloc[:,20]
#server8 = list.iloc[:,21]
tactic1 = list.iloc[:,2]
#tactic2 = list.iloc[:,23]
#tactic3 = list.iloc[:,24]
#tactic4 = list.iloc[:,25]
#tactic5 = list.iloc[:,26]

In [70]:
masterArray[:,1] = server1
masterArray[:,2] = tactic1
masterArray[:,3] = latency
masterArray[:,4] = cost
masterArray[:,6] = preL
masterArray[:,7] = preC

In [54]:
hours

0         0
1         0
2         0
3         0
4         0
         ..
50623    67
50624    67
50625    67
50626    67
50627    67
Name: Total Hours, Length: 50628, dtype: int64

In [59]:
hours[50627]-44

23

In [72]:
ii = 1
jj = 0 

for ii in range(33041,50627):

    if (hours[ii] - 266) == 71:
        break
    if server1[ii] == 1 and tactic1[ii] == 1:
        time = hours[ii] - 44
        masterArray[ii,6] = s1t1_predict_l[time]
        masterArray[ii,7] = s1t1_predict_c[time]
    if server1[ii] == 2 and tactic1[ii] == 1:
        time = hours[ii] - 44
        masterArray[ii,6] = s1t1_predict_l[time]
        masterArray[ii,7] = s1t1_predict_c[time]
    if server1[ii] == 3 and tactic1[ii] == 1:
        time = hours[ii] - 44
        masterArray[ii,6] = s1t1_predict_l[time]
        masterArray[ii,7] = s1t1_predict_c[time]
#if server4[ii] == 1 and tactic1[ii] == 1:
#    time = hours[ii] - 266
#    masterArray[ii,6] = s1t1_predict_l[time]
#    masterArray[ii,7] = s1t1_predict_c[time]
#if server5[ii] == 1 and tactic1[ii] == 1:
#    time = hours[ii] - 266
#    masterArray[ii,6] = s1t1_predict_l[time]
#    masterArray[ii,7] = s1t1_predict_c[time]
#    if server6[ii] == 1 and tactic1[ii] == 1:
#    time = hours[ii] - 266
#    masterArray[ii,6] = s1t1_predict_l[time]
#    masterArray[ii,7] = s1t1_predict_c[time]
#    if server7[ii] == 1 and tactic1[ii] == 1:
#    time = hours[ii] - 266
#    masterArray[ii,6] = s1t1_predict_l[time]
#    masterArray[ii,7] = s1t1_predict_c[time]
#    if server8[ii] == 1 and tactic1[ii] == 1:
#    time = hours[ii] - 266
#    masterArray[ii,6] = s1t1_predict_l[time]
#    masterArray[ii,7] = s1t1_predict_c[time]
#    if tactic2[ii] == 1:
#    masterArray[ii,6] = tactic2Latency
#    masterArray[ii,7] = tactic2Cost
#    if tactic3[ii] == 1:
#    masterArray[ii,6] = tactic3Latency
#    masterArray[ii,7] = tactic3Cost
#    if tactic4[ii] == 1:
#    masterArray[ii,6] = tactic4Latency
#    masterArray[ii,7] = tactic4Cost
#    if tactic5[ii] == 1:
#    masterArray[ii,6] = tactic5Latency
#    masterArray[ii,7] = tactic5Cost

In [80]:
#The arima model generator outputted averages for Tactics 2 through 5, so the values are static. 
tactic2Latency = 0.001777754
tactic2Cost = 0.3252611
tactic3Latency = 0.0000270675
tactic3Cost = 0.3155018
tactic4Latency = 0.03531913
tactic4Cost = 0.325499
tactic5Latency = 0.02110524
tactic5Cost = 0.2585247

In [73]:
np.savetxt("arimaApache.csv", masterArray, delimiter=",")

In [141]:
#Do not use, old version

m = 0
p = 0
for j in range(45954, 57442):
    if p == 34:
        break
    
    if (predictTime[p] + 3604) < j:
        p = p + 1
        
    if predictTime[p] < j:
        #print(predictTime[p],j - 1)
        #print(masterArray[s1t1counter,0],j)
        if j == masterArray[s1t1counter,0]:
            #print((predictTime[p] - 3000),j)
            masterArray[s1t1counter,6] = s1t1_predict_l[p]
            masterArray[s1t1counter,7] = s1t1_predict_c[p]
            s1t1counter = s1t1counter + 1
        if j == masterArray[s2t1counter,0]:
            #print((predictTime[p] - 3000),j)
            masterArray[s2t1counter,6] = s2t1_predict_l[p]
            masterArray[s2t1counter,7] = s2t1_predict_c[p]
            s2t1counter = s2t1counter + 1
        if j == masterArray[s3t1counter,0]:
           
            masterArray[s3t1counter,6] = s3t1_predict_l[p]
            masterArray[s3t1counter,7] = s3t1_predict_c[p]
            s3t1counter = s3t1counter + 1
        if j == masterArray[s4t1counter,0]:
         
            masterArray[s4t1counter,6] = s4t1_predict_l[p]
            masterArray[s4t1counter,7] = s4t1_predict_c[p]
            s4t1counter = s4t1counter + 1
        if j == masterArray[s5t1counter,0]:
            masterArray[s5t1counter,6] = s5t1_predict_l[p]
            masterArray[s5t1counter,7] = s5t1_predict_c[p]
            s5t1counter = s5t1counter + 1
        if j == masterArray[s6t1counter,0]:
           
            masterArray[s6t1counter,6] = s6t1_predict_l[p]
            masterArray[s6t1counter,7] = s6t1_predict_c[p]
            s6t1counter = s6t1counter + 1
        if j == masterArray[s7t1counter,0]:
   
            masterArray[s7t1counter,6] = s7t1_predict_l[p]
            masterArray[s7t1counter,7] = s7t1_predict_c[p]
            s7t1counter = s7t1counter + 1
        if j == masterArray[s8t1counter,0]:
            
            masterArray[s8t1counter,6] = s8t1_predict_l[p]
            masterArray[s8t1counter,7] = s8t1_predict_c[p]
            s8t1counter = s8t1counter + 1

NameError: name 'predictTime' is not defined

In [136]:
np.savetxt("arimaFinalnorm.csv", masterArray, delimiter=",")